name: Run Translation Script

# Triggers: Schedule and manual execution
on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:  # Allows manual execution from the Actions tab

jobs:
  run_script:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use Python 3.8

      # Step 3: Install required Python libraries
      - name: Install dependencies
        run: |
          pip install transformers requests sentencepiece  # Added sentencepiece

      # Step 4: Run the script
      - name: Run translation script
        run: python cryptonews_translator.py

      # Step 5: Commit and push changes back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add translated_news.json
          git commit -m "Update translated news"
          git push origin main
